/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package kr.ac.ajou.dsd.kda.api.model;


/**
 * @author Jae wook
 * Model class for translation  
 */
public class Transliteration {
	
	
	private java.lang.String result;

 	public void setResult(java.lang.String result) {
		this.result = result;
	}

	public java.lang.String getResult() {
		return result;
	}

	
	private java.lang.String text;

 	public void setText(java.lang.String text) {
		this.text = text;
	}

	public java.lang.String getText() {
		return text;
	}

}