language: java

jdk:
  - oraclejdk8

deploy:
  provider: openshift
  user: danielchabr@gmail.com
  password:
    secure: js2szWt3DQRiIWPRSJIqfxJcEnGmoNyvc13JWnD5vEzF+NnmwHMDRaVn1FO/XPJNsTD03+q96/mqhPdWIW4jJGXmcZ7AdhksCWbsRrnBbiwd/lbKyh7oAyoONHtqPXsBJ6wWK21sMiC3GYSvLoYqw75ZsaY0NReULivg6aAOwKSQouvQxmPV0AC1TSm+5Wen3zHUkoFSgz+feM7QnR58/3duE/15tj7r7pd8p6FjQclkyScyGGX81nXP8OY56nmFDQ6n69J+8wnb3AgT8OSZyJhlzfHGwfnpmhGVjknarw0nxm5fwRDttbG7T+XuZOf7/rYzgZ5G0yXR8eczpZ2R3vFW8nmrMii9+8AMVxs1odsfrJQ450RRGic/IBOo5OErMttLSmrP+Je93Fv5eA6kMIUVLkJWpO+23oYyGgM8cBgS9U82PUreS+nigffGmTqQNyamMLPytj2jdLpbkTxidBkFSlYvJOcKVI7/pspKHy6wsTlcQteJh5iGV4o4SOqmtYq6fqGU3Ggnry2aeAoBBHgqHvXvTk0Vh+e6aNNm8dkzyxYXSmOKkwLnQEQWIoMltG50M80yiazWUx2j9gdd8QtLq2mJzOC/GuCUdXAjzqoDTvx6+BuKZaZdvZv8UrrhI3P987rpyCV+DngxX/L3FXuUQHonMeXzhRSxAH/d+mo=
  app: kda
  domain: damell
  on:
    repo: Damell/Korean-dining-advisor
