language: java

jdk:
  - oraclejdk8

deploy:
  provider: openshift
  user: danielchabr@gmail.com
  password:
    secure: iC2BAAPeLLos1ZpZ+GhTPTYHUcbiIYmEHRgU7vlSGkAYO6dLddubbPddY/lF6eCOcjguGEGYyn2XC5lC2oPnZPGDbwiVpqksiK5KST2y3iEH+Ww52ysMSmof9exb2Pt/fF4ZXlygtrgB6VHN5bNM7Uv76CAn8OVcb4CGiC5YP/hwY4+usUIsqo62R5gAYtLn7SbivRcFZYarzpg6jBk6fqj92PkMZJQ6Mxaj0334nbeJPd/z5y11Ia+3YanCGhSh3OV1g+0eGPww2AX7qtL4jukz71XwA8WInB7W5Exilr1xSNpOFV0fSk8lhPL2i+eyoRcGecL5LEKsnWtZH1EchEFQpPRKWM9tsIOsK9jRl3P9COlY4Rl/JS7kVVN300g7FciX76PAGCDuybMqtftx67s1TeGi04UcHkxxU1gCx3waXbGLfWkhg+8bsh3MqCBoYcZ2JlgDPnlm2ASsounW3Ho8r9clcgNqfJMevAyerj7GfBUEfPgkBMCfTj3rtRy9L3Pd7ujVDunJt5zjkzOD/vevj0NNusuOQ74GEnXASLR34x354hkWX8iK4WZceS9BHouW9L5j7JdcwJghNNeNEvtvjMUb/C0RGWfGT3SuAMvEwG+SwQcgwMq4pFXINi8kvD7911tCsCAh5MMjEyktJKEKsJIy7YQ2fqlfH716+nI=
  app: kda
  domain: damell
  on:
    repo: Damell/Korean-dining-advisor
